spring:
   profiles:
      active:
        - dev
---
server:
  port: 8201

spring:
  profiles: dev
  application:
      name: micoconfig-test-client5

eureka:
 client:
  service-url:
    defaultZone: http://admin:enjoy@localhost:7001/eureka
info:
  app.name: micocloud-config-client-dev2
  company.name: enjoy
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: micoconfig-test-client5

eureka:
 client:
  service-url:
    defaultZone: http://admin:enjoy@localhost:7001/eureka
info:
  app.name: micocloud-config-client-dev
  company.name: enjoy
